# Generated by Django 2.0.10 on 2022-09-03 14:14

import bmat.api.models.reports
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('input_file', models.FileField(help_text='CSV file to process', upload_to=bmat.api.models.reports.Report.rename_uuid)),
                ('pid', models.TextField(help_text='Celery ID task', null=True)),
                ('output_file', models.TextField(help_text='CSV file path resulting', null=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Working'), (1, 'Done')], default=0, help_text='Status could be 0: Processing, 1: Done')),
            ],
            options={
                'ordering': ['-created', '-modified'],
            },
        ),
    ]
